### ISSUE TITLE
Design Docs

### ISSUE THREAD

**Issue by Vanchen07** [jbubar/allama#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://open.appacademy.io/learn/swe-in-person/full-stack-project/mvp-checklist) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments
- will users be able to delete projects?

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments

---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments

---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
- for GET /api/users , do you anticipate needing to get all users?
- what's the reasoning for the nested routes?

---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments
- are you planning to share one session form for both sign in and sign up?
- for your `/home/:userId` route, are you planning to be able to see a home page for other users(besides the currently signed in user)?
- same question for your routes with :userId

**Comment by jbubar** [comment]
### Hey Vanessa! 
_Thanks for going over my design docs and providing me with this feedback. 
I am going to try to answer all of your questions bellow 🐳_

### MVP List
1.  Yes. I plan on being able to delete a project, section and task. So there will be CRUD actions for those three. I will update my MVP list to reflect that.

### Back End Routes
2. for GET /api/users , Good catch.. I do not want all users... I just want all of the users on a specific team. 
I changed it to 
```diff
- GET /api/team/:id/users - returns information
+ GET /api/team/:id/users - returns users on a team information
+ GET /api/users/:id - returns a single user's info
```
Here is an example on Asana.com where they list all of the team members in one place.
![Screen Shot 2020-12-03 at 10 59 00 PM](https://user-images.githubusercontent.com/53061723/101132044-2886a000-35bb-11eb-9a28-a3e7f4a8674e.png)

3. The nested routes are because I need all of the project or users on a specific team. It is a way for me to specify a team... Do you have another suggestion? I struggled a bit with this..

### Front End Routes
> are you planning to share one session form for both sign in and sign up?
4. Good catch on the front end routes with my signup form. I guess I got a bit sloppy
```diff
* /signup
-     * SessionForm
+     * SignupForm
```
>for your /home/:userId route, are you planning to be able to see a home page for other users(besides the currently signed in user)?
5. The home page should be the same for everyone on the same team.
>same question for your routes with :userId
6. This is a good question. I need to think about it. I think yes. I would like you to be able to see the pages of everyone on your team. 

_Let me know if I answered your questions fully. I would love to talk to you, because I am making some assumptions with my whole design that I am not sure about. 🤷‍♂️_

**Comment by jbubar** [comment]
Hey Vanessa! 
I think I completed my user auth, but I was having trouble pushing it to heroku.
got a red wall full of errors. Ill put in a question tomorrow morning :)
![Screen Shot 2020-12-10 at 12 36 41 AM](https://user-images.githubusercontent.com/53061723/101745557-12c41f80-3a80-11eb-9ce9-9b68bf771f3a.png)
![Screen Shot 2020-12-10 at 12 36 51 AM](https://user-images.githubusercontent.com/53061723/101745575-13f54c80-3a80-11eb-83e3-367d00944cc7.png)
